### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by RoeHH** [lianstuder/.dotfiles#1]
Was isch das für es repo?

**Comment by lianstuder** [comment]
Configuration files

**Comment by RoeHH** [comment]
Zu lit

**Comment by lianstuder** [comment]
genau

**Comment by RoeHH** [comment]
| <!doctype html><html class="no-js" dir="ltr" loc="de"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><title>WhatsApp Web</title><meta name="viewport" content="width=device-width"><meta name="google" content="notranslate"><meta name="format-detection" content="telephone=no"/><meta name="description" content="Sende und empfange einfach WhatsApp Nachrichten direkt von deinem Computer."><meta name="og:description" content="Sende und empfange einfach WhatsApp Nachrichten direkt von deinem Computer."/><meta name="og:url" content="https://web.whatsapp.com/"/><meta name="og:title" content="WhatsApp Web"/><meta name="og:image" content="https://static.facebook.com/images/whatsapp/www/whatsapp-promo.png"/><link id="favicon" rel="shortcut icon" href="/img/favicon/1x/favicon.png" type="image/png"/><link rel="apple-touch-icon" sizes="194x194" href="/apple-touch-icon.png" type="image/png"/><style>#app,body,html{height:100%;width:100%;overflow:hidden;padding:0;margin:0}#app{position:absolute;top:0;left:0}#initial_startup,#startup{width:100%;height:100%;position:fixed;background-color:#f0f0f0;-moz-user-select:none;-webkit-user-select:none;display:flex;align-items:center;justify-content:center;display:-webkit-box;display:-webkit-flex;-webkit-align-items:center;-webkit-justify-content:center;flex-direction:column;-webkit-flex-direction:column}.spinner-container{-webkit-animation:rotate 2s linear infinite;animation:rotate 2s linear infinite;z-index:2}.spinner-path{stroke-dasharray:1,150;stroke-dashoffset:0;stroke:#acb9bf;stroke-linecap:round;-webkit-animation:dash 1.5s ease-in-out infinite;animation:dash 1.5s ease-in-out infinite}@keyframes rotate{100%{transform:rotate(360deg)}}@-webkit-keyframes rotate{100%{-webkit-transform:rotate(360deg)}}@keyframes dash{0%{stroke-dasharray:1,150;stroke-dashoffset:0}50%{stroke-dasharray:90,150;stroke-dashoffset:-35}100%{stroke-dasharray:90,150;stroke-dashoffset:-124}}@-webkit-keyframes dash{0%{stroke-dasharray:1,150;stroke-dashoffset:0}50%{stroke-dasharray:90,150;stroke-dashoffset:-35}100%{stroke-dasharray:90,150;stroke-dashoffset:-124}}.progress-container{width:360px;position:fixed;padding-top:120px;top:50%;left:50%;margin-left:-180px}progress{-webkit-appearance:none;appearance:none;width:100%;height:3px;border:none;margin:0;color:#00d9bb;background-color:#e6e6e6}progress[value]::-webkit-progress-bar{background-color:#e6e6e6}progress[value]::-webkit-progress-value{background-color:#00d9bb;transition:width .45s ease}progress[value]::-moz-progress-bar{background-color:#00d9bb;transition:width .45s ease}</style><link href="/bootstrap_qr-fbb6a00121541f35de3f.css" rel="stylesheet"></head><body class="web"><script>try{var systemThemeDark,theme=window.localStorage.getItem("theme"),systemThemeMode=window.localStorage.getItem("system-theme-mode");if(("true"===systemThemeMode\|\|!theme)&&window.matchMedia){var systemTheme=window.matchMedia("(prefers-color-scheme: dark)");systemThemeDark=systemTheme&&systemTheme.matches}('"dark"'===theme\|\|systemThemeDark)&&document.body.classList.add("dark")}catch(e){}</script><div id="app"/><div id="hard_expire_time" data-time="1630784359.308"></div><div id="initial_startup"><svg class="spinner-container" width="50" height="50" viewBox="0 0 44 44"><circle class="spinner-path" cx="22" cy="22" r="20" fill="none" stroke-width="4"></circle></svg></div><scripts src="/../output/moment_locales/de.f8ca46b171e5c84d0242.js.map"><scripts src="/../output/moment_locales/de.f8ca46b171e5c84d0242.js.map"><script>/*! Copyright (c) 2021 WhatsApp Inc. All Rights Reserved. */var __webpack_modules__,__webpack_module_cache__;__webpack_modules__={14859:e=>{e.exports=function(e){return e&&e.__esModule?e:{default:e}}},80521:(e,t)=>{"use strict";var r;Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;try{r=window.localStorage}catch(e){}var n=r;t.default=n},61941:(e,t)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=function(e,t="?"){if(null==e)throw new Error("Unexpected null or undefined: ".concat(t));return e}},43443:(e,t)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getDistribution=function(){return"".concat("web","_").concat("prod")},t.getLogUserAgent=function({appVersion:e,browser:t,device:r}){var n;return n="Web/"+t,"WhatsApp/".concat(e," ").concat(n," Device/").concat(r)}},81498:(e,t,r)=>{"use strict";var n=r(14859),o=n(r(80521)),a=n(r(61941)),c=r(43443),u=r(85049);function i(e){!function(e,t){var r=window.navigator.userAgent;if(r!==w\|\|!e.includes("getElementsByTagName")){var n=new FormData,i=new Blob([e],{type:"text/plain"});n.append("from",function(){if(l)return l;try{(l=JSON.parse((0,a.default)(o.default,"localStorage").getItem(f)))&&(l=l.replace("-",""))}catch(e){}if(!l){l="unknown"+Math.floor(1e10*Math.random());try{(0,a.default)(o.default,"localStorage").setItem(f,JSON.stringify(l))}catch(e){}}return l}()),n.append("agent",(0,c.getLogUserAgent)((0,u.parseUASimple)(r,d))),n.append("file",i,"logs.txt"),n.append("tags","load");var s=new XMLHttpRequest,g=_+"?access_token="+encodeURIComponent(p);s.open("POST",g,!0),s.send(n)}}(e)}function s({error:e,reason:t,stack:r}){var n=(new Date).toISOString();return"".concat(n,": error: ").concat(e,"\n").concat(n,": reason for logs: ").concat(t,"\n").concat(n,": userAgent: ").concat(window.navigator.userAgent,"\n").concat(r)}null==window.onerror&&(window.onerror=function(e,t,r){return"Uncaught SyntaxError: Unexpected token '<'"===e?(function(e){var t=e.split("/")[3].replace(/^\//,"");i(s({error:"failed to load a js or css bundle",reason:"failed to load [".concat(t,"]"),stack:""}))}(t),!0):(i(s({error:e,reason:"Error at [".concat(t,":").concat(r,"]"),stack:""})),!1)});var l,d="2.2108.8",_="https://crashlogs.whatsapp.net/wa_clb_data",p="1063127757113399\|745146ffa34413f9dbb5469f5370b7af",f="WAUnknownID",w="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"},85049:(e,t)=>{"use strict";function r(e){return e.includes("windows")?"Windows":e.includes("mac")?"Mac OS":e.includes("linux")?"Linux":"Unparsed"}Object.defineProperty(t,"__esModule",{value:!0}),t.parseUASimple=function(e,t){var n=e.toLowerCase();return{browser:c(n),device:r(n),appVersion:t}};var n=/(chrome\|firefox)\/([\w\.]+)/i,o=/(edge\|opr)\/([\w\.]+)/i,a={chrome:"Chrome",edge:"Edge",opr:"Opera",firefox:"Firefox"};function c(e){var t=e.match(o)\|\|e.match(n);return null==t?"Unparsed":"".concat(a[t[1]]," ").concat(t[2])}}},__webpack_module_cache__={},function e(t){if(__webpack_module_cache__[t])return __webpack_module_cache__[t].exports;var r=__webpack_module_cache__[t]={exports:{}};return __webpack_modules__[t](r,r.exports,e),r.exports}(81498)</script><script defer="defer" src="/vendor1~bootstrap_qr.69e960b196d7d6aa3d46.js"></script><script defer="defer" src="/bootstrap_qr.8c6bd07fd55e4b8fbdb7.js"></script></scripts></scripts></body></html>
-- | --
